### Different ways to create tensors

In [1]:
import torch
import numpy as np

In [2]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])


In [3]:
# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

Tensor from array: tensor([11, 12, 13, 14, 15])


#### Different functions for creating tensors:
##### torch.empty(), torch.ones(), and torch.zeros()

In [4]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[-5.7661e-13,  4.5465e-41, -5.7661e-13,  4.5465e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.3631e-44,  0.0000e+00,  1.3902e-38,  0.0000e+00]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

tensor_rand_un : tensor([[0.3285, 0.5111, 0.8633, 0.7608, 0.2312],
        [0.7997, 0.8148, 0.6695, 0.0097, 0.7165],
        [0.4134, 0.5817, 0.4679, 0.3066, 0.5928],
        [0.7984, 0.1921, 0.9098, 0.0800, 0.1378]])
tensor_rand_norm : tensor([[-1.3877,  0.9404, -1.4361, -0.7351,  0.3164],
        [ 0.2022, -1.2747, -0.5341,  1.4639, -0.6222],
        [-1.2884, -0.2795, -0.9693,  0.3308, -0.1377],
        [-0.2036, -1.1447,  0.7205, -0.7928, -0.2182]])
tensor_rand_int : tensor([[8, 5, 5, 8, 5],
        [8, 9, 9, 6, 6],
        [6, 8, 7, 7, 6],
        [8, 5, 6, 8, 7]])


In [6]:
# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [14]:
t1 = torch.ones((2,3),dtype= torch.int)
t1

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [15]:
t2 = torch.ones_like(t1)
t2

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [16]:
t3 = torch.arange(1,10,3)
t3

tensor([1, 4, 7])

In [18]:
t4 = torch.arange(1,11).reshape(2,5)
t4

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])