###Tensor operations

In [1]:
import torch

In [2]:
#@title Indexing 1-dim tensor example
one_dim_tensor=torch.tensor([1,2,3,4,5,6,7,8])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor(3)
3


In [4]:
one = torch.tensor([1,2,3,4,5])
print(one[2])
print(one[2].item())

tensor(3)
3


In [5]:
#@title Slicing 1-dim tensor example
# [start:end:step]
one_dim_tensor[1:4]

tensor([2, 3, 4])

In [6]:
#@title Indexing 2-dim tensor example
two_dim_tensor=torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
two_dim_tensor[1][3]

tensor(10)

In [7]:
print(two_dim_tensor)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])


In [10]:
two_dim_tensor[1,1:3]

tensor([8, 9])

In [11]:
#@title Slicing 2-dim tensor example
print("first three elements of the 1st row: ",two_dim_tensor[0, 0:3])
print("first four elements of the 2nd row: ",two_dim_tensor[1,0:4])

first three elements of the 1st row:  tensor([1, 2, 3])
first four elements of the 2nd row:  tensor([ 7,  8,  9, 10])


In [12]:
#@title Use indexing to extract the data that meets some criteria
two_dim_tensor[two_dim_tensor<11]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#@title Combining tensors
torch.stack((two_dim_tensor, two_dim_tensor))

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

In [14]:
#@title Splitting tensors
first_tensor, second_tensor, third_tensor, fourth_tensor=torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5, 6]) tensor([ 7,  8,  9, 10, 11, 12]) tensor([13, 14, 15, 16, 17, 18]) tensor([19, 20, 21, 22, 23, 24])


In [16]:
#@title Splitting 2-dim tensor
a = torch.unbind(two_dim_tensor,dim=1)

In [17]:
print(a)

(tensor([ 1,  7, 13, 19]), tensor([ 2,  8, 14, 20]), tensor([ 3,  9, 15, 21]), tensor([ 4, 10, 16, 22]), tensor([ 5, 11, 17, 23]), tensor([ 6, 12, 18, 24]))


In [26]:
print(a[0])

tensor([ 1,  7, 13, 19])
